logging:
  level:
    root: INFO
    com.example.inventory: DEBUG

server:
  port: 8083

spring:
  application:
    name: msvc-inventory

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:mysql-service}:${MYSQL_PORT:3306}/${MYSQL_DB:inventory}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
      database: mysql
      database-platform: org.hibernate.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST:redis-service}
      port: ${REDIS_PORT:6379}
      lettuce:
        pool:
          enabled: false

  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq-service}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD}
