name: Backend CI

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    name: Build & Test - microservice-auth
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Compilar microservice-auth
        working-directory: backend/microservice-auth
        run: ./mvnw clean package -DskipTests

      - name: Mostrar resultado
        run: echo "✅ Build completado correctamente"
